// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/calendar": {
            "get": {
                "description": "Get Calendar Events",
                "tags": [
                    "Calendar"
                ],
                "summary": "Get Calendar Events",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetCalendarEventsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetCalendarEventsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/day_offs": {
            "post": {
                "description": "Create day off",
                "tags": [
                    "DayOffs"
                ],
                "summary": "Create day off",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateDayOffRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateDayOffResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/day_offs/{day_off_id}": {
            "get": {
                "description": "get day off",
                "tags": [
                    "DayOffs"
                ],
                "summary": "Get day off",
                "parameters": [
                    {
                        "type": "string",
                        "description": "day_off_id",
                        "name": "day_off_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetDayOffResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete day off",
                "tags": [
                    "DayOffs"
                ],
                "summary": "Delete day off",
                "parameters": [
                    {
                        "type": "string",
                        "description": "day_off_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/export/reports": {
            "get": {
                "description": "Export reports to csv",
                "tags": [
                    "Reports"
                ],
                "summary": "Export reports to csv",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetReportsRequest"
                        }
                    }
                ],
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/profile": {
            "get": {
                "description": "Getting user data",
                "tags": [
                    "Profile"
                ],
                "summary": "Get Profile",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetProfileResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updating user data",
                "tags": [
                    "Profile"
                ],
                "summary": "Update Profile",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports": {
            "get": {
                "description": "get all reports",
                "tags": [
                    "Reports"
                ],
                "summary": "Get all reports",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetReportsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetReportsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create report",
                "tags": [
                    "Reports"
                ],
                "summary": "Create report",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateReportResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/{report_id}": {
            "get": {
                "description": "get report",
                "tags": [
                    "Reports"
                ],
                "summary": "Get report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "report_id",
                        "name": "report_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetReportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update report",
                "tags": [
                    "Reports"
                ],
                "summary": "Update report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "report_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete report",
                "tags": [
                    "Reports"
                ],
                "summary": "Delete report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "report_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/send_mail": {
            "post": {
                "description": "Send email",
                "tags": [
                    "Email"
                ],
                "summary": "Send email",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SendEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sick_leaves": {
            "post": {
                "description": "Create sick leave",
                "tags": [
                    "SickLeaves"
                ],
                "summary": "Create sick leave",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateSickLeaveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateSickLeaveResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sick_leaves/{sick_leave_id}": {
            "get": {
                "description": "get sick leave",
                "tags": [
                    "SickLeaves"
                ],
                "summary": "Get sick leave",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sick_leave_id",
                        "name": "sick_leave_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetSickLeaveResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete sick leave",
                "tags": [
                    "SickLeaves"
                ],
                "summary": "Delete sick leave",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sick_leave_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sign_in": {
            "post": {
                "description": "Getting an authorization token",
                "tags": [
                    "Auth"
                ],
                "summary": "Sign In",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SignInResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sign_up": {
            "post": {
                "description": "User registration",
                "tags": [
                    "Auth"
                ],
                "summary": "Sign Up",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/stats": {
            "get": {
                "description": "Get Statistics",
                "tags": [
                    "Statistics"
                ],
                "summary": "Get Statistics",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetStatisticsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetStatisticsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Get Users",
                "tags": [
                    "Users"
                ],
                "summary": "Get Users",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.GetUsersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetUsersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{user_id}/permissions": {
            "post": {
                "description": "Give the user permission to read an object",
                "tags": [
                    "Permission"
                ],
                "summary": "Add object to user permission",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AddObjectToUserPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove the user's permission to read an object",
                "tags": [
                    "Permission"
                ],
                "summary": "Remove object from user permission",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AddObjectToUserPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vacations": {
            "post": {
                "description": "Create vacation",
                "tags": [
                    "Vacation"
                ],
                "summary": "Create vacation",
                "parameters": [
                    {
                        "description": "body params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateVacationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateVacationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/vacations/{vacation_id}": {
            "get": {
                "description": "get vacation",
                "tags": [
                    "Vacation"
                ],
                "summary": "Get vacation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "vacation_id",
                        "name": "vacation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GetVacationResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete vacation",
                "tags": [
                    "Vacation"
                ],
                "summary": "Delete vacation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "vacation_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperror.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AddObjectToUserPermissionRequest": {
            "type": "object",
            "properties": {
                "object_id": {
                    "type": "string"
                },
                "object_type": {
                    "type": "string"
                }
            }
        },
        "domain.CalendarEvent": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "event_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateDayOffRequest": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "domain.CreateDayOffResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateReportRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "break_time": {
                    "type": "integer"
                },
                "date": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "work_time": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateReportResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateSickLeaveRequest": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "domain.CreateSickLeaveResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateVacationRequest": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "description": "todo *",
                    "type": "string"
                },
                "is_paid": {
                    "type": "boolean"
                }
            }
        },
        "domain.CreateVacationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.DayOff": {
            "type": "object",
            "properties": {
                "creator_id": {
                    "type": "string"
                },
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.GetCalendarEventsRequest": {
            "type": "object",
            "properties": {
                "allowed_to": {
                    "type": "string"
                },
                "date_from": {
                    "type": "string"
                },
                "date_to": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "domain.GetCalendarEventsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CalendarEvent"
                    }
                }
            }
        },
        "domain.GetDayOffResponse": {
            "type": "object",
            "properties": {
                "sick_leave": {
                    "$ref": "#/definitions/domain.DayOff"
                }
            }
        },
        "domain.GetProfileRequest": {
            "type": "object"
        },
        "domain.GetProfileResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                }
            }
        },
        "domain.GetReportResponse": {
            "type": "object",
            "properties": {
                "report": {
                    "$ref": "#/definitions/domain.Report"
                }
            }
        },
        "domain.GetReportsRequest": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "string"
                },
                "date_to": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "domain.GetReportsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "reports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ReportItem"
                    }
                }
            }
        },
        "domain.GetSickLeaveResponse": {
            "type": "object",
            "properties": {
                "sick_leave": {
                    "$ref": "#/definitions/domain.SickLeave"
                }
            }
        },
        "domain.GetStatisticsRequest": {
            "type": "object",
            "properties": {
                "from_date": {
                    "type": "integer"
                },
                "to_date": {
                    "type": "integer"
                }
            }
        },
        "domain.GetStatisticsResponse": {
            "type": "object",
            "properties": {
                "avg_hours_break": {
                    "type": "integer"
                },
                "avg_hours_worked": {
                    "type": "integer"
                },
                "avg_start_time": {
                    "type": "integer"
                },
                "hours_worked": {
                    "type": "integer"
                }
            }
        },
        "domain.GetUsersRequest": {
            "type": "object",
            "properties": {
                "allowed_to": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "domain.GetUsersResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.UsersItem"
                    }
                }
            }
        },
        "domain.GetVacationResponse": {
            "type": "object",
            "properties": {
                "vacation": {
                    "$ref": "#/definitions/domain.Vacation"
                }
            }
        },
        "domain.Report": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "break_time": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "creator_id": {
                    "type": "string"
                },
                "date": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                },
                "work_time": {
                    "type": "integer"
                }
            }
        },
        "domain.ReportItem": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "break_time": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "creator_id": {
                    "type": "string"
                },
                "date": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                },
                "work_time": {
                    "type": "integer"
                }
            }
        },
        "domain.SendEmailRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "recipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "domain.SickLeave": {
            "type": "object",
            "properties": {
                "creator_id": {
                    "type": "string"
                },
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.SignInRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.SignInResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "domain.SignUpRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateReportRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "break_time": {
                    "type": "integer"
                },
                "date": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "work_time": {
                    "type": "integer"
                }
            }
        },
        "domain.UsersItem": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "domain.Vacation": {
            "type": "object",
            "properties": {
                "creator_id": {
                    "type": "string"
                },
                "date_from": {
                    "type": "integer"
                },
                "date_to": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_paid": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "httperror.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httperror.ErrorResponseError"
                }
            }
        },
        "httperror.ErrorResponseDetails": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "httperror.ErrorResponseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httperror.ErrorResponseDetails"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Reporter API",
	Description:      "This is a report server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
