basePath: /api/v1
definitions:
  domain.AddObjectToUserPermissionRequest:
    properties:
      object_id:
        type: string
      object_type:
        type: string
      user_id:
        type: string
    type: object
  domain.CreateReportRequest:
    properties:
      body:
        type: string
      break_time:
        type: integer
      date:
        type: integer
      display_name:
        type: string
      end_time:
        type: integer
      start_time:
        type: integer
      work_time:
        type: integer
    type: object
  domain.CreateReportResponse:
    properties:
      id:
        type: string
    type: object
  domain.GetProfileRequest:
    type: object
  domain.GetProfileResponse:
    properties:
      display_name:
        type: string
      id:
        type: string
      login:
        type: string
    type: object
  domain.GetReportResponse:
    properties:
      report:
        $ref: '#/definitions/domain.Report'
    type: object
  domain.GetReportsRequest:
    properties:
      date_from:
        type: string
      date_to:
        type: string
      page:
        type: integer
      page_size:
        type: integer
    type: object
  domain.GetReportsResponse:
    properties:
      count:
        type: integer
      reports:
        items:
          $ref: '#/definitions/domain.ReportItem'
        type: array
    type: object
  domain.GetStatisticsRequest:
    properties:
      from_date:
        type: integer
      to_date:
        type: integer
    type: object
  domain.GetStatisticsResponse:
    properties:
      avg_hours_break:
        type: integer
      avg_hours_worked:
        type: integer
      avg_start_time:
        type: integer
      hours_worked:
        type: integer
    type: object
  domain.GetUsersRequest:
    properties:
      page:
        type: integer
      page_size:
        type: integer
    type: object
  domain.GetUsersResponse:
    properties:
      count:
        type: integer
      reports:
        items:
          $ref: '#/definitions/domain.UsersItem'
        type: array
    type: object
  domain.Report:
    properties:
      body:
        type: string
      break_time:
        type: integer
      created_at:
        type: integer
      creator_id:
        type: string
      date:
        type: integer
      display_name:
        type: string
      end_time:
        type: integer
      id:
        type: string
      start_time:
        type: integer
      updated_at:
        type: integer
      work_time:
        type: integer
    type: object
  domain.ReportItem:
    properties:
      body:
        type: string
      break_time:
        type: integer
      created_at:
        type: integer
      creator_id:
        type: string
      date:
        type: integer
      display_name:
        type: string
      end_time:
        type: integer
      id:
        type: string
      start_time:
        type: integer
      updated_at:
        type: integer
      work_time:
        type: integer
    type: object
  domain.SendEmailRequest:
    properties:
      body:
        type: string
      email:
        type: string
      password:
        type: string
      recipients:
        items:
          type: string
        type: array
      subject:
        type: string
    type: object
  domain.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  domain.SignInResponse:
    properties:
      token:
        type: string
    type: object
  domain.SignUpRequest:
    properties:
      display_name:
        type: string
      login:
        type: string
      password:
        type: string
    type: object
  domain.UpdateProfileRequest:
    properties:
      display_name:
        type: string
    type: object
  domain.UpdateReportRequest:
    properties:
      body:
        type: string
      break_time:
        type: integer
      date:
        type: integer
      display_name:
        type: string
      end_time:
        type: integer
      start_time:
        type: integer
      work_time:
        type: integer
    type: object
  domain.UsersItem:
    properties:
      display_name:
        type: string
      id:
        type: string
      login:
        type: string
    type: object
  httperror.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/httperror.ErrorResponseError'
    type: object
  httperror.ErrorResponseDetails:
    properties:
      description:
        type: string
      position:
        type: string
      reason:
        type: string
    type: object
  httperror.ErrorResponseError:
    properties:
      code:
        type: integer
      description:
        type: string
      details:
        items:
          $ref: '#/definitions/httperror.ErrorResponseDetails'
        type: array
    type: object
info:
  contact: {}
  description: This is a report server.
  title: Reporter API
  version: 0.0.1
paths:
  /api/v1/export/reports:
    get:
      description: Export reports to csv
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetReportsRequest'
      responses:
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Export reports to csv
      tags:
      - Reports
  /api/v1/profile:
    get:
      description: Getting user data
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetProfileRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetProfileResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Get Profile
      tags:
      - Profile
    put:
      description: Updating user data
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateProfileRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Update Profile
      tags:
      - Profile
  /api/v1/reports:
    get:
      description: get all reports
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetReportsRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetReportsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Get all reports
      tags:
      - Reports
    post:
      description: Create report
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateReportRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.CreateReportResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Create report
      tags:
      - Reports
  /api/v1/reports/{report_id}:
    delete:
      description: Delete report
      parameters:
      - description: report_id
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Delete report
      tags:
      - Reports
    get:
      description: get report
      parameters:
      - description: report_id
        in: path
        name: report_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetReportResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Get report
      tags:
      - Reports
    put:
      description: Update report
      parameters:
      - description: report_id
        in: path
        name: id
        required: true
        type: string
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateReportRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Update report
      tags:
      - Reports
  /api/v1/send_mail:
    post:
      description: Send email
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SendEmailRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Send email
      tags:
      - Email
  /api/v1/sign_in:
    post:
      description: Getting an authorization token
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SignInRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignInResponse'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Sign In
      tags:
      - Auth
  /api/v1/sign_up:
    post:
      description: User registration
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Sign Up
      tags:
      - Auth
  /api/v1/stats:
    get:
      description: Get Statistics
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetStatisticsRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetStatisticsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Get Statistics
      tags:
      - Statistics
  /api/v1/users:
    get:
      description: Get Users
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.GetUsersRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GetUsersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Get Users
      tags:
      - Users
  /api/v1/users/{user_id}/permissions:
    delete:
      description: Remove the user's permission to read an object
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.AddObjectToUserPermissionRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Remove object from user permission
      tags:
      - Permission
    post:
      description: Give the user permission to read an object
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.AddObjectToUserPermissionRequest'
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperror.ErrorResponse'
      summary: Add object to user permission
      tags:
      - Permission
swagger: "2.0"
