version: "3.3"

services:
  database:
    image: ovsienko023/reporter-db:v1.1.0
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: ovsienko023/reporter-api:v1.1.0
    restart: unless-stopped
    command: ./reporter
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database:
