#version: "3.3"
#
#services:
##  database:
##    build:
##      context: ./database
##      dockerfile: Dockerfile
##    restart: unless-stopped
###    ports:
###      - "5442:5432"
##    volumes:
##      - database:/var/lib/postgresql/data
#  server:
#    build:
#      context: ./api
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    command: ./reporter
##    depends_on:
##      - database
#    ports:
#      - "8888:8888"
#    networks:
#      - default
#
##volumes:
##  database:

version: "3.3"

services:
  database:
    image: ovsienko023/reporter-db:v1.0.1
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: ovsienko023/reporter-api:v1.0.1
    restart: unless-stopped
    command: ./reporter
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database:
