version: "3.3"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5442:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    command: go run main.go
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database: