version: "3.3"

services:
  database:
    image: ovsienko023/reporter-database:v1.1.6
    restart: unless-stopped
    ports:
      - "5442:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: ovsienko023/reporter-api:v1.1.11
    restart: unless-stopped
    command: ./reporter
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database:
