version: "3.3"

services:
  database:
    container_name: reported_db
    platform: linux/amd64
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5442:5432"
    volumes:
      - database:/var/lib/postgresql/data
  api:
    container_name: reported_api
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    command: ./reporter
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database:
