version: "3.3"

services:
  database:
    platform: linux/amd64
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5442:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ./reporter
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default

volumes:
  database:
